b-it-bots: FJ6LazOM
BARC: YEnzHu6P
Donaxi: yNgF6huI
homer: D2wydiJX
Pumas: LY1Eyhk5
SocRob: EKY3GZUe
Ursus: 9Y303emH
Watermelon: tDmOnKzw
ROSolution: O6HZs2Bo
Trinity: 2M0Vf5wZ

DefaultTeam: DefaultKey
DumpTeam: randomkey
TestingTeam: PASSWORD
